services:
  loki:
    image: grafana/loki:latest
    container_name: porygon-loki
    ports:
      - "3100:3100"
    networks:
      - porygon-network
    volumes:
      - .loki-grafana/loki-config.yaml:/etc/loki/config.yaml
      - .loki-grafana/loki:/loki
    command: -config.file=/etc/loki/config.yaml

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - porygon-network

  porygon:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: porygon
    restart: always
    env_file:
      - .env
    environment:
      SERVER_URL: ${SERVER_URL}
      LOKI_URL: http://loki:3100
      SERVER_LABEL: ${SERVER_LABEL}
    depends_on:
      - loki
      - grafana
    ports:
      - "5000:5000"

networks:
  porygon-network:
    driver: bridge